version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GREENLIGHT_DB_NAME: ${GREENLIGHT_DB_NAME}
      GREENLIGHT_DB_USER: ${GREENLIGHT_DB_USER}
      GREENLIGHT_DB_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      GREENLIGHT_DB_DSN: ${GREENLIGHT_DB_DSN}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - greenlight-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      GREENLIGHT_DB_NAME: ${GREENLIGHT_DB_NAME}
      GREENLIGHT_DB_USER: ${GREENLIGHT_DB_USER}
      GREENLIGHT_DB_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      GREENLIGHT_DB_DSN: ${GREENLIGHT_DB_DSN}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - greenlight-network

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "${GREENLIGHT_DB_DSN}",
        "up",
      ]
    depends_on:
      - db
    networks:
      - greenlight-network

volumes:
  db_data:

networks:
  greenlight-network:
