#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GREENLIGHT_DB_USER WITH PASSWORD '$GREENLIGHT_DB_PASSWORD';
    CREATE DATABASE $GREENLIGHT_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $GREENLIGHT_DB_NAME TO $GREENLIGHT_DB_USER;
    \c $GREENLIGHT_DB_NAME
    ALTER ROLE $GREENLIGHT_DB_USER WITH LOGIN;
    ALTER ROLE $GREENLIGHT_DB_USER WITH CREATEDB;
    ALTER ROLE $GREENLIGHT_DB_USER WITH CREATEROLE;
    ALTER ROLE $GREENLIGHT_DB_USER WITH INHERIT;
    ALTER ROLE $GREENLIGHT_DB_USER WITH NOREPLICATION;
    ALTER ROLE $GREENLIGHT_DB_USER WITH CONNECTION LIMIT -1;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$GREENLIGHT_DB_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS citext;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $GREENLIGHT_DB_USER;
EOSQL