#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE $DATABASE_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE_NAME TO $DATABASE_USER;
    \c $DATABASE_NAME
    ALTER ROLE $DATABASE_USER WITH LOGIN;
    ALTER ROLE $DATABASE_USER WITH CREATEDB;
    ALTER ROLE $DATABASE_USER WITH CREATEROLE;
    ALTER ROLE $DATABASE_USER WITH INHERIT;
    ALTER ROLE $DATABASE_USER WITH NOREPLICATION;
    ALTER ROLE $DATABASE_USER WITH CONNECTION LIMIT -1;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DATABASE_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS citext;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DATABASE_USER;
EOSQL
