#!/bin/bash
set -e

# Use DATABASE_NAME if set, otherwise default to POSTGRES_DB
DB_NAME=${DATABASE_NAME:-$POSTGRES_DB}

echo "Using the following environment variables:"
echo "POSTGRES_USER: $POSTGRES_USER"
echo "POSTGRES_DB: $POSTGRES_DB"
echo "DATABASE_USER: $DATABASE_USER"
echo "DATABASE_PASSWORD: $DATABASE_PASSWORD"
echo "DB_NAME: $DB_NAME"
echo "DATABASE_DSN: $DATABASE_DSN"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DATABASE_USER WITH PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE $DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DATABASE_USER;
    \c $DB_NAME
    ALTER ROLE $DATABASE_USER WITH LOGIN;
    ALTER ROLE $DATABASE_USER WITH CREATEDB;
    ALTER ROLE $DATABASE_USER WITH CREATEROLE;
    ALTER ROLE $DATABASE_USER WITH INHERIT;
    ALTER ROLE $DATABASE_USER WITH NOREPLICATION;
    ALTER ROLE $DATABASE_USER WITH CONNECTION LIMIT -1;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_NAME" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS citext;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DATABASE_USER;
EOSQL
